package com.hoosiercoder.dispatchtool.ticket.controller;

import com.hoosiercoder.dispatchtool.ticket.dto.TicketDTO;
import com.hoosiercoder.dispatchtool.ticket.service.TicketService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/**
 * Author: HoosierCoder
 *
 */
@RestController
@RequestMapping("/api/v1/ticket")
public class TicketController {
    @Autowired
    private TicketService ticketService;

    @PostMapping
    public ResponseEntity createTicket(@Valid @RequestBody TicketDTO ticketDTO) {
        ticketDTO.setTicketId(null);//ID is autogenerated in service, null out.

        TicketDTO newTicketDTO = ticketService.saveNewTicket(ticketDTO);

        return ResponseEntity.ok(newTicketDTO);//return ResponseEntity.ok(newUserDto);
    }

    @GetMapping
    public ResponseEntity<List<TicketDTO>> getTickets() {

        List<TicketDTO> tickets = ticketService.listTickets();

        if (tickets.isEmpty()) {
            //No return (204) returned
            return ResponseEntity.noContent().build();
        }

        return ResponseEntity.ok(tickets);
    }

    @GetMapping("/{ticketId}")
    public ResponseEntity getTicketById(@PathVariable String ticketId) {
        Optional<TicketDTO> ticket = ticketService.getByTicketId(ticketId);

        if (ticket.isEmpty()) {
            return ResponseEntity.notFound().build();
        }

        return ResponseEntity.ok(ticket);
    }

    @GetMapping("/unassigned")
    public ResponseEntity<List<TicketDTO>> getUnassignedTickets() {

        List<TicketDTO> tickets = ticketService.findUnassignedTickets();

        if (tickets.isEmpty()) {
            //No return (204) returned
            return ResponseEntity.noContent().build();
        }

        return ResponseEntity.ok(tickets);
    }

    @GetMapping("/open")
    public ResponseEntity<List<TicketDTO>> getOpenTickets() {

        List<TicketDTO> tickets = ticketService.listOpenTickets();

        if (tickets.isEmpty()) {
            //No return (204) returned
            return ResponseEntity.noContent().build();
        }

        return ResponseEntity.ok(tickets);
    }

    @GetMapping("/byUsers")
    public ResponseEntity<List<TicketDTO>> getByUserId(@PathVariable Long userId) {

        List<TicketDTO> tickets = ticketService.findByUser(userId);

        if (tickets.isEmpty()) {
            //No return (204) returned
            return ResponseEntity.noContent().build();
        }

        return ResponseEntity.ok(tickets);
    }
}
